services:
  db:
    image: postgres:16
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"   # <— host:container
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: ecommerce_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pg_data: