"""catalog with UUID everywhere

Revision ID: d55b5acc16c3
Revises: e64f80be94b5
Create Date: 2025-09-12 12:06:15.471680
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd55b5acc16c3'
down_revision: Union[str, Sequence[str], None] = 'e64f80be94b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'brands',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('slug', sa.String(length=140), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug')
    )
    op.create_table(
        'categories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug')
    )
    op.create_table(
        'products',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=220), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('material', sa.String(length=140), nullable=True),
        sa.Column('care', sa.String(), nullable=True),
        sa.Column('gender', sa.String(length=16), nullable=True),
        sa.Column('season', sa.String(length=16), nullable=True),
        sa.Column('fit', sa.String(length=32), nullable=True),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('category_id', sa.UUID(), nullable=True),
        sa.Column('brand_id', sa.UUID(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    op.create_table(
        'product_images',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('url', sa.String(length=512), nullable=False),
        sa.Column('alt_text', sa.String(length=200), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'product_variants',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('sku', sa.String(length=64), nullable=False),
        sa.Column('barcode', sa.String(length=64), nullable=True),
        sa.Column('size_label', sa.String(length=24), nullable=False),
        sa.Column('color_name', sa.String(length=32), nullable=False),
        sa.Column('color_hex', sa.String(length=7), nullable=True),
        sa.Column('stock_on_hand', sa.Integer(), nullable=False),
        sa.Column('stock_reserved', sa.Integer(), nullable=False),
        sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sku')
    )

    # Campos extra en users (users ya existe por e64f80be94b5)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('address_line1', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('address_line2', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('oauth_sub', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_picture', sa.String(length=512), nullable=True))
    # 🔻 QUITADO: updated_at (ya existe en init users)
    # op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'hashed_password', existing_type=sa.VARCHAR(), nullable=True)
    op.create_index('ix_user_oauth_provider_sub', 'users', ['oauth_provider', 'oauth_sub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_user_oauth_provider_sub', table_name='users')
    op.alter_column('users', 'hashed_password', existing_type=sa.VARCHAR(), nullable=False)
    # (no tocamos updated_at porque no lo agregamos aquí)
    op.drop_column('users', 'oauth_picture')
    op.drop_column('users', 'oauth_sub')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'country')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address_line2')
    op.drop_column('users', 'address_line1')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'email_verified')
    op.drop_table('product_variants')
    op.drop_table('product_images')
    op.drop_table('products')
    op.drop_table('categories')
    op.drop_table('brands')
